### ISSUE TITLE
Support py2 and py3 (or auto pick python version from virtual env)

### ISSUE THREAD

**Issue by sotte** [5long/pytest-vim-compiler#3]
I just rediscovered pytest-vim-compiler when I was cleaning my vimrc. Great tool! Don't know why I forgot about it.

It would be cool if pytest-vim-compiler would pick up the python version from the virtual environment or at least allow to specify what python version should be used.

**Comment by sotte** [comment]
This did the trick for me:

```
CompilerSet makeprg=.venv/bin/python\ -m\ pytest\ --tb=short\ -q
```

Note that `.venv/` is my virtual env.

**Comment by blueyed** [comment]
Currently it uses just `py.test`, which should also get picked up from the $PATH, no?
Don't you have the `bin` dir of your `$VIRTUAL_ENV` there?

**Comment by sotte** [comment]
My virtualenv is in `.venv/` of each project. But there was a `py.test` in the site-packages (which I thought should not be used) and that was a 2.7 version. After uninstalling that version the correct py.test from the venv was used.

(I also had to deactivate some plugins but that is unrelated.)

Thanks!

**Comment by 5long** [comment]
@sotte 

In case you might have missed this: the recommended way to use virtualenv is to [activate it](http://docs.python-guide.org/en/latest/dev/virtualenvs/) before working on the project. Activating a virtualenv will add `ENV/bin` to your `$PATH`, which will allow you to launch `ENV/bin/py.test` by executing `py.test`.

Automagically detecting local virtualenv might be good. But there's no single most popular way to organize virtualenv as far as I know:
- `.venv/` is a reasonable choice I guess.
- I'm using [virtualenvwrapper](https://bitbucket.org/dhellmann/virtualenvwrapper), which works well for me.
- At where I work, we're installing virtualenv in `venv/` and NOT gonna activate it. Instead, we have an in-house PAAS which requires me to use a custom script to launch any executables in the virtualenv. Totally non-standard, but gotta live with it.

So um, I believe activating virtualenv before launching vim should be good enough for this vim compiler works for most people.

**Comment by sotte** [comment]
@5long ya, the venv is activated of course, all the dependencies are picked up and whatnot. Thanks though!
